# Generated by Django 3.0.14 on 2022-03-29 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='specialized_subjects',
            field=models.ManyToManyField(related_name='teachers', to='courses.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(check=models.Q(('birth__gte', '1900-01-01'), ('birth__lte', '2022-01-01')), name='ch_tc_birth_from_01-01-1900_to_01-01-2022'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('birth__gte', '1900-01-01'), ('birth__lte', '2022-01-01')), name='ch_st_birth_from_01-01-1900_to_01-01-2022'),
        ),
    ]
